title:              Hramos93
email:              ramoshumbertoa6@gmail.com
description:        Personal Blog
author:             Humberto Ramos
baseurl:            ""
url:                "https://Hramos93.github.io"

# Social Profiles
twitter_username:   RamosHumberto93
github_username:    Hramos93
facebook_username:  
instagram_username:  Hramos93
linkedin_username:   Hramos93

# Add your google-analytics ID here to activate google analytics
google_analytics:   G-8RQKY58DNL # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
highlighter: rouge 

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  shortname: hramos93-github-io